development:
  database: dfqhdfbbr5jpes
  user: qqqlbzhjmcazfc
  password: f23ee4c2b4790aa628676b05286470bf95c524c2e8d934be670eaf289fc3cc75
  host: ec2-54-75-244-161.eu-west-1.compute.amazonaws.com
  adapter: postgresql
  log: true

test:
  database: headwords
  host: localhost
  adapter: sqlite
  user:
  password:
  log: true

production:
  database: headwords
  host: localhost
  adapter: postgresql
